apiVersion: v1
kind: Pod
metadata:
  name: red-pod
  namespace: red
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name":"attachnet","namespace":"red","ips":["172.30.0.2/24"]}]'
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]